version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    # replace username/repo:tag with your name and image details
    image: bkake/boot-docker:v1
    #Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
    deploy:
        mode: replicated
        replicas: 5
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
            condition: on-failure
            delay: 10s
    ports:
      - 8080
    networks:
      - webnet
networks:
  webnet: